env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
ignorePatterns: [build]
rules: {
  react/function-component-definition: 0,
  import/no-cycle: 0,
  react-hooks/rules-of-hooks: 0,
  react-hooks/exhaustive-deps: 0
}
