name: Deploy to Rollbar

on: push

jobs:
  deploy:
    runs-on: macos-10.14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Rollbar
        uses: rollbar/rollbar-deploy-github-action@v1
        with:
          rollbarAccessToken: ${{ c25695d18a2e4454ae98432b59249a0e }}
          environment: production
          revision: ${{ nightshiftmaster }}
