steps:
  - name: Notify deploy to Rollbar
    uses: rollbar/github-deploy-action@2.1.1
    id: rollbar_deploy
    with:
      environment: "production"
      version: ${{ github.sha }}
    env:
      ROLLBAR_ACCESS_TOKEN: ${{ 4a0b163990a24902bcfc430f475ab690 }}
      ROLLBAR_USERNAME: ${{ nightshiftmaster }}
